on:
  workflow_call:
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1
      - name: Checkout
        uses: actions/checkout@v1
      - name: Make
        run: make ci
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2
