# This workflow is the standard Go workflow with the addition of the SQL-based
# persistence mechanisms supported by Dogmatiq projects.

on:
  workflow_call:

jobs:
  go:
    name: Go + SQL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Make (with CGO)
        run: make ci
        env:
          CGO_ENABLED: "1"
          DOGMATIQ_TEST_DSN_MYSQL_MYSQL: "root:rootpass@tcp(127.0.0.1:${{ job.services.mysql.ports['3306'] }})/mysql"
          DOGMATIQ_TEST_DSN_MARIADB_MYSQL: "root:rootpass@tcp(127.0.0.1:${{ job.services.mariadb.ports['3306'] }})/mysql"
          DOGMATIQ_TEST_DSN_POSTGRESQL_PGX: "user=postgres password=rootpass sslmode=disable host=127.0.0.1 port=${{ job.services.postgres.ports['5432'] }}"
          DOGMATIQ_TEST_DSN_POSTGRESQL_POSTGRES: "postgres://postgres:rootpass@127.0.0.1:${{ job.services.postgres.ports['5432'] }}?sslmode=disable"

      - name: Make (tests only, without CGO)
        run: make test
        env:
          CGO_ENABLED: "0"
          DOGMATIQ_TEST_DSN_MYSQL_MYSQL: "root:rootpass@tcp(127.0.0.1:${{ job.services.mysql.ports['3306'] }})/mysql"
          DOGMATIQ_TEST_DSN_MARIADB_MYSQL: "root:rootpass@tcp(127.0.0.1:${{ job.services.mariadb.ports['3306'] }})/mysql"
          DOGMATIQ_TEST_DSN_POSTGRESQL_PGX: "user=postgres password=rootpass sslmode=disable host=127.0.0.1 port=${{ job.services.postgres.ports['5432'] }}"
          DOGMATIQ_TEST_DSN_POSTGRESQL_POSTGRES: "postgres://postgres:rootpass@127.0.0.1:${{ job.services.postgres.ports['5432'] }}?sslmode=disable"

      - name: Upload coverage report
        uses: codecov/codecov-action@v3

    services:
      mysql:
        image: mysql:8
        options: >-
          --mount type=tmpfs,destination=/var/lib/mysql
          --health-cmd="mysqladmin ping --host 127.0.0.1 --port 3306 --user root --password=rootpass"
          --health-interval 2s
          --health-timeout 10s
          --health-start-period 30s
          --health-retries 10
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpass

      mariadb:
        image: mariadb:10
        options: >-
          --mount type=tmpfs,destination=/var/lib/mysql
          --health-cmd="mysqladmin ping --host 127.0.0.1 --port 3306 --user root --password=rootpass"
          --health-interval 2s
          --health-timeout 10s
          --health-start-period 30s
          --health-retries 10
        ports:
          - 3306/tcp
        env:
          MARIADB_ROOT_PASSWORD: rootpass

      postgres:
        image: postgres:13
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 10s
          --health-start-period 30s
          --health-retries 10
        ports:
          - 5432/tcp
        env:
          POSTGRES_PASSWORD: rootpass
