on:
  workflow_call:

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Make
        run: make ci

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
