on:
  workflow_call:

jobs:
  dependabot:
    name: Merge PR
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Load Dependabot meta-data
        uses: dependabot/fetch-metadata@v1.1.1
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge minor/patch updates to in-house dependencies
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --merge --auto
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'github.com/dogmatiq') && steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
