on:
  workflow_call:

jobs:
  go:
    name: Go + Minio
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v3

      - name: Make
        run: make ci
        env:
          DOGMATIQ_TEST_MINIO_ACCESS_KEY: minio
          DOGMATIQ_TEST_MINIO_SECRET_KEY: password
          DOGMATIQ_TEST_MINIO_ENDPOINT: "http://localhost:${{ job.services.minio.ports['9000'] }}"

      - name: Upload coverage report
        uses: codecov/codecov-action@v3

    services:
      minio:
        image: minio/minio:edge-cicd
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-interval 2s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 9000/tcp
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: password
