name: CI

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Check formatting
        run: terraform fmt -check

      - name: Initialize
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve -input=false
